"""auto_load start/end_date

Revision ID: 081969076993
Revises: d36dcb4310aa
Create Date: 2020-08-30 01:17:06.940241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081969076993'
down_revision = 'd36dcb4310aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('just_for_test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'just_for_test')
    # ### end Alembic commands ###
