"""crypto

Revision ID: 1397f5e3c99e
Revises: 39aa3b977230
Create Date: 2020-08-07 21:00:48.356096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1397f5e3c99e'
down_revision = '39aa3b977230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('crypto', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_crypto'), 'user', ['crypto'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_crypto'), table_name='user')
    op.drop_column('user', 'crypto')
    # ### end Alembic commands ###
