"""ftp_creds

Revision ID: a1268cade721
Revises: e420c86ad9fa
Create Date: 2020-10-19 10:54:02.292983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1268cade721'
down_revision = 'e420c86ad9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('ftp_login', sa.String(length=100), nullable=True))
    op.add_column('integration', sa.Column('ftp_pass', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'ftp_pass')
    op.drop_column('integration', 'ftp_login')
    # ### end Alembic commands ###
