"""integration auto_load

Revision ID: a20fa262e071
Revises: 36e362d2a9e4
Create Date: 2020-08-28 03:06:28.420627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20fa262e071'
down_revision = '36e362d2a9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('auto_load', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'auto_load')
    # ### end Alembic commands ###
