"""empty message

Revision ID: ac52a512b702
Revises: e420c86ad9fa
Create Date: 2020-09-22 19:17:02.544996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac52a512b702'
down_revision = 'e420c86ad9fa'
branch_labels = None
depends_on = None


def upgrade():
	pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('integration', sa.Column('callback_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'callback_url')
    # ### end Alembic commands ###
