"""callback urls

Revision ID: e420c86ad9fa
Revises:
Create Date: 2020-09-22 14:15:40.615582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e420c86ad9fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('role',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=True),
    # sa.Column('description', sa.String(length=256), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('email', sa.String(length=100), nullable=True),
    # sa.Column('crypto', sa.String(length=100), nullable=True),
    # sa.Column('password_hash', sa.String(length=100), nullable=True),
    # sa.Column('name', sa.String(length=1000), nullable=True),
    # sa.Column('active', sa.Boolean(), nullable=True),
    # sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_crypto'), 'user', ['crypto'], unique=True)
    # op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # op.create_table('integration',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('integration_name', sa.String(length=100), nullable=True),
    # sa.Column('api_key', sa.String(length=100), nullable=True),
    # sa.Column('user_domain', sa.String(length=100), nullable=True),
    # sa.Column('metrika_key', sa.String(length=100), nullable=True),
    # sa.Column('metrika_counter_id', sa.Integer(), nullable=True),
    # sa.Column('auto_load', sa.Boolean(), nullable=True),
    # sa.Column('start_date', sa.Date(), nullable=True),
    # sa.Column('callback_url', sa.String(length=100), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('message',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('recipient_id', sa.Integer(), nullable=True),
    # sa.Column('body', sa.String(length=140), nullable=True),
    # sa.Column('timestamp', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    # op.create_table('notification',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=128), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('timestamp', sa.Float(), nullable=True),
    # sa.Column('payload_json', sa.Text(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    # op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    # op.create_table('roles_users',
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('role_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    # )
    # op.create_table('task',
    # sa.Column('id', sa.String(length=36), nullable=False),
    # sa.Column('name', sa.String(length=128), nullable=True),
    # sa.Column('description', sa.String(length=128), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('complete', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_table('integration')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_crypto'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
