"""integration end-start date

Revision ID: d36dcb4310aa
Revises: a20fa262e071
Create Date: 2020-08-29 01:52:54.134958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36dcb4310aa'
down_revision = 'a20fa262e071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('integration', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'start_date')
    op.drop_column('integration', 'end_date')
    # ### end Alembic commands ###
