"""saved search

Revision ID: f171b6745c56
Revises: 1937b0e8839f
Create Date: 2020-10-28 19:01:30.636034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f171b6745c56'
down_revision = '1937b0e8839f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ch_query', sa.String(length=10000), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_search')
    # ### end Alembic commands ###
